[package]
name = "termfm"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.29"
tui = "0.19.0"
toml = "0.9.5"
chrono = "0.4"
ncurses = "6.0.1"
dirs = "6.0.0"
libc = "0.2.175"
termion = "4.0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
